name: Deploy Docs
on:
  push:
    branches:
      - page
jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          registry-url: 'https://registry.npmmirror.com/'
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Generate Docs
        run: pnpm build:docs
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs