name: Publish Package
on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '22'
          registry-url: 'https://registry.npmmirror.com/'
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Build dist
        run: pnpm prepublishOnly
      - name: Publish to npm
        run: pnpm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}